virt: lxd

dist: focal

script:
- cat /etc/os-release
- curl -LO https://github.com/k3s-io/k3s/releases/download/v1.23.3%2Bk3s1/k3s
- chmod +x k3s
- sudo ./k3s server --kubelet-arg=feature-gates=KubeletInUserNamespace=true --kube-controller-manager-arg=feature-gates=KubeletInUserNamespace=true --kube-apiserver-arg=feature-gates=KubeletInUserNamespace=true &
#- curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#- chmod +x ./kubectl
#- systemctl status k3s.service
- sudo ./k3s kubectl get nodes
