#virt: lxd

#dist: focal

#script:
#- cat /etc/os-release
#- curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
#- mv minikube-linux-amd64 minikube
#- chmod +x minikube
#- ./minikube start --driver=docker
#- docker ps
#- curl -LO https://github.com/k3s-io/k3s/releases/download/v1.23.3%2Bk3s1/k3s
#- chmod +x k3s
#- sudo ./k3s server --kubelet-arg=feature-gates=KubeletInUserNamespace=true --kube-controller-manager-arg=feature-gates=KubeletInUserNamespace=true --kube-apiserver-arg=feature-gates=KubeletInUserNamespace=true &
#- curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#- chmod +x ./kubectl
#- systemctl status k3s.service
#- sudo ./k3s kubectl get nodes

os: linux
dist: xenial
language: php
group: dev
php:
  - 7.3
  - 8.1
  - 7.4

script:
#- wget https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/20133803/+files/libargon2-dev_0~20190702-0.1+ubuntu18.04.1+deb.sury.org+1_amd64.deb
#- sudo dpkg -i libargon2-dev_0~20190702-0.1+ubuntu18.04.1+deb.sury.org+1_amd64.deb
- php --version
