virt: lxd

dist: focal

script:
- cat /etc/os-release
- curl -sfL -o k3s https://github.com/k3s-io/k3s/releases/download/v1.23.3%2Bk3s1/k3s
- sudo ./k3s server &
#- systemctl status k3s.service
- sudo kubectl get nodes
